name: Build and Upload Artifact

# 触发工作流的事件
on:
  push:
    branches:
      - kaylor
  pull_request:
    branches:
      - kaylor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run build script
      run: |
        bash build.sh

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: kit
    #     path: kit.tar.gz 